# .pre-commit-config.yaml
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.1  # Use the latest stable release
    hooks:
      - id: ruff
        args: ["--fix"]  # Enable ruff to fix formatting issues
        stages: [commit]  # Only run on staged files

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable release
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
